Repository Tikam02/DevOps-Guide, pull requests merged in 2019-11, with the labels that each got.

#10 fix some typos
  Docker/docker-concepts.md
  Docker/readme.md
Labels: documentation

#15 Fix my website
  README.md
Labels: bug

#18 Add AWS cloudformation
  IaC/Cloudformation/cloudformation-concepts.md
  IaC/Cloudformation/cloudformation-tutorials.md
  IaC/Cloudformation/readme.md
Labels: enhancement

#20 Add Travis CI Sections
  CI-CD/TravisCi/Readme.md
  CI-CD/TravisCi/travis-commands.md
  CI-CD/TravisCi/travis-concepts.md
  README.md
  img/logo/travisci.png
Labels: enhancement

#22 Update gitlab-commands.md
  CI-CD/GitlabCi/gitlab-commands.md
Labels: documentation, enhancement

#34 Fixed errata
  OS/os-commands.md
Labels: enhancement, good first issue
